version: "3.8"
services:
  gs4d:
    build: .
    image: gs4d:runpod
    container_name: gs4d
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    command: ["python", "tools/train.py", "--help"]
