name: gs4d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.2.2
  - torchvision==0.17.2
  - pytorch-cuda=12.1
  - numpy=1.24.3
  - pip
  - pip:
    - opencv-python>=4.5.0
    - imageio>=2.9.0
    - imageio-ffmpeg>=0.4.5
    - Pillow>=9.0.0
    - scipy>=1.7.0
    - scikit-learn>=0.24.0
    - tqdm>=4.62.0
    - PyYAML>=5.4.0
    - pandas>=1.3.0
    - h5py>=3.0.0
    - matplotlib>=3.3.0
    - gsplat==0.1.11